pipeline {
    agent  {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "211125615103"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // Build
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('BASTION ACM EKS INGRESS-ALB ') {
            parallel {
                stage('Trigger BASTION') {
                    steps {
                        script {
                            build job: '20-bastion', 
                            propagate: false,  // even SG fails VPC will not be effected
                            wait: false // VPC will not wait for SG pipeline completion
                        }
                    }
                }
                stage('ACM ALB') {
                    // sequental
                    stages {
                        stage('Trigger ACM') {
                            steps {
                                script {
                                build job: '60-acm', 
                                propagate: false,  // even SG fails VPC will not be effected
                                wait: false // VPC will not wait for SG pipeline completion
                                }
                            }
                        }
                        stage('Trigger ALB') {
                            steps {
                                script {
                                build job: '70-ingress-alb', 
                                propagate: false,  // even SG fails VPC will not be effected
                                wait: false // VPC will not wait for SG pipeline completion
                                }
                            }
                        }
                    }
                }
                stage('Trigger EKS') {
                    steps {
                        script {
                            build job: '80-eks', 
                            propagate: false,  // even SG fails VPC will not be effected
                            wait: false // VPC will not wait for SG pipeline completion
                        }
                    }
                }              
            }
                
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}